"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { apiRequest } from "@/lib/api-client";

type Settings = { engine_enabled: boolean; ai_generation_enabled: boolean; sending_enabled: boolean; mode: string; approval_required: boolean; max_push_per_user_per_day: number; allowed_start_time: string; allowed_end_time: string; timezone: string };
type Campaign = { id: string; name: string; category: string; status: string; scheduled_at: string | null; audience_definition: { type?: string } };
type Dashboard = { settings: Settings; today: { sent_today: number; scheduled_today: number; pending_approval: number }; upcoming: Campaign[] };
type Analytics = { totals: { sent: number; failed: number; opened: number; open_rate: number | null } };

const categories = ["feature_discovery", "premium", "education", "engagement", "reactivation", "personal_finance", "group_expenses", "reminders", "savings", "reports", "receipt_ai", "seasonal"];
const statusStyle: Record<string, string> = { draft: "bg-slate-100 text-slate-700", pending_approval: "bg-amber-100 text-amber-800", approved: "bg-sky-100 text-sky-800", scheduled: "bg-indigo-100 text-indigo-800", sent: "bg-emerald-100 text-emerald-800", partially_sent: "bg-orange-100 text-orange-800", failed: "bg-rose-100 text-rose-800", cancelled: "bg-slate-200 text-slate-700" };
const dateText = (value: string | null) => value ? new Intl.DateTimeFormat("es-CL", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Sin programar";
function Label({ children }: { children: React.ReactNode }) { return <span className="text-xs font-semibold uppercase tracking-wide text-slate-500">{children}</span>; }

export function PushMarketingClient() {
  const [dashboard, setDashboard] = useState<Dashboard | null>(null); const [campaigns, setCampaigns] = useState<Campaign[]>([]); const [analytics, setAnalytics] = useState<Analytics | null>(null); const [loading, setLoading] = useState(true); const [message, setMessage] = useState<string | null>(null); const [count, setCount] = useState(8); const [category, setCategory] = useState("feature_discovery"); const [startDate, setStartDate] = useState(""); const [endDate, setEndDate] = useState(""); const [dailyFrequency, setDailyFrequency] = useState(1);
  const load = useCallback(async () => { setLoading(true); try { const [d, c, a] = await Promise.all([apiRequest<Dashboard>("/admin/push/dashboard"), apiRequest<Campaign[]>("/admin/push/campaigns?limit=40"), apiRequest<Analytics>("/admin/push/analytics")]); setDashboard(d); setCampaigns(c); setAnalytics(a); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo cargar Push Marketing."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const patch = async (value: Partial<Settings>) => { try { const settings = await apiRequest<Settings>("/admin/push/settings", { method: "PATCH", body: JSON.stringify(value) }); setDashboard((current) => current ? { ...current, settings } : current); setMessage("Configuración actualizada."); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo actualizar."); } };
  const generate = async (event: FormEvent) => { event.preventDefault(); try { const result = await apiRequest<{ generated: number }>("/admin/push/campaigns/generate", { method: "POST", body: JSON.stringify({ count, categories: [category], objective: "engagement", start_date: startDate || undefined, end_date: endDate || undefined, daily_frequency: dailyFrequency }) }); setMessage(`${result.generated} campañas creadas como borradores.`); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudieron generar campañas."); } };
  const action = async (id: string, actionName: "approve" | "cancel") => { try { await apiRequest(`/admin/push/campaigns/${id}/${actionName}`, { method: "POST" }); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "La acción no pudo completarse."); } };
  const settings = dashboard?.settings;
  return <main className="min-h-screen bg-slate-50 px-4 py-8 text-slate-900 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl space-y-7">
    <header className="flex flex-col gap-4 border-b border-slate-200 pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-emerald-700">TEILEN ADMIN</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Push Marketing</h1><p className="mt-2 text-sm text-slate-600">Campañas con IA, revisión humana y controles de entrega en backend.</p></div><button onClick={() => void load()} className="rounded-md border border-slate-300 bg-white px-4 py-2 text-sm font-semibold hover:bg-slate-100">Actualizar</button></header>
    {message && <div className="rounded-md border border-slate-200 bg-white px-4 py-3 text-sm">{message}</div>}
    {loading || !dashboard ? <div className="rounded-lg border border-slate-200 bg-white p-8 text-sm text-slate-500">Cargando estado del motor…</div> : <>
      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["Motor", settings?.engine_enabled ? "Activo" : "Detenido"], ["Modo", settings?.mode], ["IA", settings?.ai_generation_enabled ? "Activa" : "Pausada"], ["Envíos", settings?.sending_enabled ? "Activos" : "Pausados"], ["Aprobación", settings?.approval_required ? "Obligatoria" : "Opcional"]].map(([label, value]) => <div key={label} className="rounded-lg border border-slate-200 bg-white p-4"><Label>{label}</Label><p className="mt-2 text-lg font-semibold">{value}</p></div>)}</section>
      <section className="grid gap-4 lg:grid-cols-[1.4fr_1fr]"><div className="rounded-lg border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Control del motor</h2><span className="text-xs text-slate-500">{settings?.timezone}</span></div><div className="mt-5 grid gap-4 sm:grid-cols-3"><div><Label>Máximo diario</Label><p className="mt-1 text-2xl font-semibold">{settings?.max_push_per_user_per_day}</p></div><div><Label>Horario</Label><p className="mt-1 text-2xl font-semibold">{String(settings?.allowed_start_time).slice(0, 5)}–{String(settings?.allowed_end_time).slice(0, 5)}</p></div><div><Label>Hoy</Label><p className="mt-1 text-2xl font-semibold">{dashboard.today.sent_today} enviadas</p></div></div><div className="mt-6 flex flex-wrap gap-3"><button onClick={() => void patch({ sending_enabled: !settings?.sending_enabled })} className="rounded-md bg-slate-900 px-4 py-2 text-sm font-semibold text-white">{settings?.sending_enabled ? "Pausar todos los envíos" : "Reanudar envíos"}</button><button onClick={() => { if (window.confirm("Esto detiene inmediatamente todos los envíos programados. ¿Continuar?")) void patch({ sending_enabled: false, engine_enabled: false }); }} className="rounded-md border border-rose-300 px-4 py-2 text-sm font-semibold text-rose-700">Detener motor</button></div></div>
      <div className="rounded-lg border border-slate-200 bg-white p-5"><h2 className="font-semibold">Métricas</h2><dl className="mt-4 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-slate-500">Enviadas</dt><dd className="mt-1 text-xl font-semibold">{analytics?.totals.sent ?? 0}</dd></div><div><dt className="text-slate-500">Fallidas</dt><dd className="mt-1 text-xl font-semibold">{analytics?.totals.failed ?? 0}</dd></div><div><dt className="text-slate-500">Abiertas</dt><dd className="mt-1 text-xl font-semibold">{analytics?.totals.opened ?? 0}</dd></div><div><dt className="text-slate-500">Open rate</dt><dd className="mt-1 text-xl font-semibold">{analytics?.totals.open_rate == null ? "N/A" : `${Math.round(analytics.totals.open_rate * 100)}%`}</dd></div></dl></div></section>
      <section className="grid gap-4 lg:grid-cols-[1fr_2fr]"><form onSubmit={generate} className="rounded-lg border border-slate-200 bg-white p-5"><h2 className="font-semibold">Generar campañas con IA</h2><p className="mt-1 text-sm text-slate-600">Siempre se crean en borrador: no se envía nada desde este formulario.</p><div className="mt-5 grid grid-cols-2 gap-3"><label><Label>Desde</Label><input value={startDate} onChange={(event) => setStartDate(event.target.value)} type="date" className="mt-1 w-full rounded-md border border-slate-300 px-2 py-2" /></label><label><Label>Hasta</Label><input value={endDate} onChange={(event) => setEndDate(event.target.value)} type="date" className="mt-1 w-full rounded-md border border-slate-300 px-2 py-2" /></label></div><label className="mt-4 block"><Label>Frecuencia diaria</Label><select value={dailyFrequency} onChange={(event) => setDailyFrequency(Number(event.target.value))} className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2"><option value={1}>1 Push al día</option><option value={2}>2 Push al día</option><option value={3}>3 Push al día</option></select></label><label className="mt-4 block"><Label>Cantidad si no hay fechas</Label><input value={count} onChange={(event) => setCount(Math.max(1, Math.min(90, Number(event.target.value))))} type="number" min="1" max="90" className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2" /></label><label className="mt-4 block"><Label>Categoría principal</Label><select value={category} onChange={(event) => setCategory(event.target.value)} className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2">{categories.map((item) => <option key={item}>{item}</option>)}</select></label><button className="mt-5 w-full rounded-md bg-emerald-700 px-4 py-2 text-sm font-semibold text-white">Generar borradores</button></form>
      <div className="rounded-lg border border-slate-200 bg-white"><div className="flex items-center justify-between px-5 py-4"><div><h2 className="font-semibold">Campañas</h2><p className="text-sm text-slate-600">Calendario y aprobaciones recientes.</p></div><Link href="/admin/push/calendar" className="text-sm font-semibold text-emerald-700">Ver calendario</Link></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="border-y border-slate-200 bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Campaña</th><th className="px-3 py-3">Fecha</th><th className="px-3 py-3">Estado</th><th className="px-3 py-3">Audiencia</th><th className="px-5 py-3" /></tr></thead><tbody>{campaigns.map((campaign) => <tr key={campaign.id} className="border-b border-slate-100"><td className="px-5 py-3"><Link href={`/admin/push/campaigns/${campaign.id}`} className="font-medium text-emerald-700">{campaign.name}</Link><p className="text-xs text-slate-500">{campaign.category}</p></td><td className="px-3 py-3 text-slate-600">{dateText(campaign.scheduled_at)}</td><td className="px-3 py-3"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${statusStyle[campaign.status] || statusStyle.draft}`}>{campaign.status}</span></td><td className="px-3 py-3 text-slate-600">{campaign.audience_definition?.type || "all"}</td><td className="px-5 py-3 text-right">{campaign.status === "draft" || campaign.status === "pending_approval" ? <button onClick={() => void action(campaign.id, "approve")} className="font-semibold text-emerald-700">Aprobar</button> : campaign.status === "approved" || campaign.status === "scheduled" ? <button onClick={() => void action(campaign.id, "cancel")} className="font-semibold text-rose-700">Cancelar</button> : null}</td></tr>)}</tbody></table></div></div></section>
    </>}</div></main>;
}
