import type { MarketingCopy } from "../marketing-copy";

export const germanMarketing: MarketingCopy = {
  nav: ["Die App", "So funktioniert's", "Tarife", "Hilfe"],
  download: "App herunterladen", freeDownload: "Kostenlos herunterladen", how: "So funktioniert's", menu: "Menü öffnen", closeMenu: "Menü schließen",
  hero: ["Weniger rechnen.", "Mehr vorhaben.", "Mehr leben."],
  intro: "Teile Gruppenausgaben und organisiere deine persönlichen Finanzen. Alles in Teilen, damit mehr Zeit zum Genießen bleibt.",
  available: "Für iOS und Android verfügbar", pillars: ["Gemeinsame Ausgaben", "Persönliche Finanzen", "Sparziele"],
  dinner: "Abendessen mit Freunden", dinnerDetail: "4 Personen · je CLP $12.000", example: "Beispiel zur Veranschaulichung in chilenischen Pesos",
  sharingTitle: "Teilen ist einfach.\nAbrechnen auch.", sharingIntro: "Vom ersten Kaffee bis zum letzten Urlaubstag: Jede Ausgabe hat ihren Platz.",
  cases: [
    {tab: "Mit Freunden", title: "Die Reise genießen.\nDie Ausgaben teilen.", description: "Erstelle eine Gruppe, erfasse, wer was bezahlt hat, und lass Teilen die Salden berechnen.", steps: ["Gruppe erstellen und einladen", "Ausgaben erfassen und aufteilen", "Sehen, wer wem etwas schuldet"], details: ["Teile den Link oder QR-Code deiner Gruppe mit allen, die dabei sind.", "Erfasse, wer bezahlt hat, und teile gleichmäßig, prozentual oder mit individuellen Beträgen auf.", "Prüfe die Salden und erfasse erfolgte Zahlungen, damit die Abrechnung klar bleibt."], link: "Gemeinsame Ausgaben entdecken", href: "/gastos-compartidos", group: "Auszeit im Süden", people: "3 Personen", rows: ["Ferienhütte", "Lebensmittel", "Benzin"], payers: ["Cami hat bezahlt", "Nico hat bezahlt", "Du hast bezahlt"], amounts: [90000, 30000, 15000], total: "Gruppensumme", resultLabel: "Anteil pro Person", result: 45000},
    {tab: "Als Paar", title: "Mehr Teamwork.\nWeniger „Wer hat bezahlt?“.", description: "Von der Miete bis zum besonderen Abendessen. Habt eure gemeinsamen Ausgaben und Salden immer im Blick.", steps: ["Euren gemeinsamen Bereich erstellen", "Nach euren Wünschen aufteilen", "Den Überblick behalten"], details: ["Eine Gruppe für euer Zuhause, euren Urlaub oder euer gemeinsames Projekt.", "Teilt jede Ausgabe gleichmäßig, prozentual oder mit individuellen Beträgen auf.", "Seht euch die Einträge gemeinsam an und erfasst erfolgte Zahlungen."], link: "So teilt ihr Ausgaben auf", href: "/dividir-gastos", group: "Unser Zuhause", people: "2 Personen", rows: ["Lebensmittel", "Freitagsessen", "Internet"], payers: ["Dani hat bezahlt", "Du hast bezahlt", "Dani hat bezahlt"], amounts: [60000, 40000, 20000], total: "Gemeinsame Summe", resultLabel: "Bei gleichmäßiger Aufteilung", result: 60000},
    {tab: "In der WG", title: "Ein Zuhause teilen.\nUnd ein gutes Gefühl.", description: "Miete, Nebenkosten und gemeinsame Einkäufe an einem Ort. Alle wissen, was sie bezahlt haben und wie hoch ihr Anteil ist.", steps: ["Die ganze WG einladen", "Gemeinsame Ausgaben eintragen", "Den Saldo jeder Person prüfen"], details: ["Erstellt eine Gruppe und teilt den Einladungslink.", "Erfasst Ausgaben und wählt aus, wer an welcher Ausgabe beteiligt ist.", "Der gemeinsame Verlauf klärt Fragen, ohne dass ihr Nachrichten durchsuchen müsst."], link: "Haushaltsausgaben organisieren", href: "/gastos-compartidos", group: "Unsere WG", people: "3 Personen", rows: ["Miete", "Strom", "Internet"], payers: ["Fran hat bezahlt", "Alex hat bezahlt", "Du hast bezahlt"], amounts: [450000, 30000, 30000], total: "Haushaltssumme", resultLabel: "Anteil pro Person", result: 170000},
    {tab: "Für dich", title: "Dein Monat.\nKlarer im Blick.", description: "Erfasse persönliche Einnahmen und Ausgaben, prüfe deine Kategorien und verfolge deine Sparziele.", steps: ["Deine Einträge erfassen", "Sehen, wofür du Geld ausgibst", "Deinen Zielen näherkommen"], details: ["Halte persönliche Einnahmen und Ausgaben in deinem eigenen Bereich fest.", "Sieh dir deine Aktivitäten und Statistiken an, um deinen Monat besser zu verstehen.", "Erstelle ein Ziel und erfasse deine Sparbeträge, um deinen Fortschritt zu sehen."], link: "Persönliche Finanzen entdecken", href: "/control-de-gastos", group: "Meine Monatsausgaben", people: "Mein persönlicher Bereich", rows: ["Lebensmittel", "Transport", "Kaffee und Ausgehen"], payers: ["Ernährung", "Mobilität", "Freizeit"], amounts: [90000, 30000, 15000], total: "Erfasste Summe", resultLabel: "Persönliche Ausgaben geordnet", result: 135000},
  ],
  calculator: "Probiere es für deinen nächsten Plan", amountLabel: "Gesamtausgabe (CLP)", peopleLabel: "Personen", perPerson: "pro Person", calculatorHint: "Gleichmäßige Aufteilung. Für andere Vereinbarungen wähle in der App Prozentsätze oder individuelle Beträge.", invalid: "Gib einen gültigen Betrag und eine Personenzahl zwischen 2 und 100 ein.", remainder: "Der Betrag lässt sich nicht genau in ganzen Pesos aufteilen: Einige Personen zahlen $1 mehr, damit die Gesamtsumme stimmt.",
  featuresTitle: "Dein Geld.\nMehr Durchblick.", featuresIntro: "Gemeinsame und persönliche Finanzen in einer App.", goalTitle: "Mach Platz für\ndeinen nächsten großen Plan.", goalDescription: "Erfasse deine persönlichen Ausgaben und verfolge deine Sparziele.", goalName: "Reise in den Süden", goalOf: "von", goalExample: "Beispiel für ein Sparziel", goalLink: "Sparziele kennenlernen",
  features: [
    {title: "Weniger tippen, mehr Zeit", description: "Scanne deine Belege mit KI und prüfe die Angaben vor dem Speichern.", href: "/dividir-gastos"},
    {title: "Rechnungen im Blick behalten", description: "Organisiere wiederkehrende Ausgaben und Erinnerungen an Fälligkeiten.", href: "/recordatorios"},
    {title: "Deine Ausgaben verstehen", description: "Sieh dir deine Aktivitäten, Kategorien und Berichte an.", href: "/control-de-gastos"},
  ],
  life: "Das Leben findet außerhalb\nvon Tabellen statt.", lifeIntro: "Habt mehr vor. Teilen hilft euch beim Abrechnen.",
  plansTitle: "Kostenlos starten.\nIn deinem Tempo wachsen.", plansIntro: "Wähle, wie du dich organisieren möchtest.", freeTitle: "Teilen Kostenlos", freeIntro: "Für den ersten Schritt zu geordneten Finanzen.", freeFeatures: ["Gemeinsame und persönliche Ausgaben", "Bis zu 3 aktive Gruppen", "Sparziele", "Bis zu 3 KI-Belegscans pro Monat"], freeCta: "Kostenlos starten",
  premiumTitle: "Teilen Premium", premiumBadge: "Mehr Möglichkeiten", premiumIntro: "Für alle, die einen Schritt weitergehen möchten.", premiumValue: "Dein nächstes Level", premiumPriceMonthly: "3.980 CLP / Monat", premiumPriceMonthlyUsd: "≈ 4,15 US$ / Monat", premiumPriceAnnual: "oder 19.990 CLP / Jahr · ≈ 21 US$", premiumFeatures: ["Unbegrenzte Gruppen und Scans", "Berichte als PDF und Excel", "Wiederkehrende Ausgaben und Raten", "Investitionen verfolgen"], premiumCta: "Premium entdecken", planNote: "Die USD-Werte sind Richtwerte und können je nach Wechselkurs variieren. Abonnements werden über den App Store oder Google Play verwaltet.",
  faqTitle: "Von Anfang an\nklar.", faqMore: "Alle Fragen ansehen", faqs: [
    {question: "Was kann ich mit Teilen machen?", answer: "Du kannst Ausgaben mit Freunden, als Paar oder in der WG teilen, persönliche Einnahmen und Ausgaben erfassen, Erinnerungen erstellen und Sparziele verfolgen. Alles in einer App."},
    {question: "Ist Teilen kostenlos?", answer: "Ja. Der kostenlose Tarif umfasst persönliche Ausgaben, bis zu 5 gemeinsame Ausgaben pro Tag, bis zu 3 aktive Gruppen, Sparziele, bis zu 3 KI-Belegscans pro Monat und bis zu 3 Erinnerungen. Premium erweitert diese Grenzen und bietet zusätzliche Funktionen. Die aktuellen Grenzen und Preise findest du in der App."},
    {question: "Bewegt Teilen mein Geld?", answer: "Nein. Teilen organisiert deine Ausgaben, berechnet Salden und ermöglicht es dir, bereits erfolgte Zahlungen zu erfassen. Überweisungen machst du auf dem Weg, den du mit den anderen vereinbarst. Ziele und Investitionen dienen der Dokumentation und sind keine Konten, auf denen dein Geld verwahrt wird."},
    {question: "Ist Teilen für iOS und Android verfügbar?", answer: "Ja. Lade Teilen im App Store oder bei Google Play herunter. In einer Gruppe können Personen mit beiden Betriebssystemen zusammenarbeiten."},
  ],
  closingTitle: "Dein nächster Plan\nbeginnt mit Teilen.", closingIntro: "Die Ausgaben im Blick. Das Leben vor dir.",
  footerDescription: "Was du teilst und was dir gehört. Mit Teilen behältst du den Überblick über deine Finanzen.", footerHeadings: ["Produkt", "Hilfe", "Rechtliches"], footerProduct: ["Ausgaben aufteilen", "Gemeinsame Ausgaben", "Persönliche Finanzen", "Sparziele", "Premium"], footerHelp: ["Hilfecenter", "Häufige Fragen", "Kontakt"], footerLegal: ["Datenschutz", "Nutzungsbedingungen", "Cookies"], madeIn: "In Chile entwickelt, für deine Pläne.", allRights: "Alle Rechte vorbehalten.",
};
