import type { MarketingCopy } from "../marketing-copy";

export const englishMarketing: MarketingCopy = {
  nav: ["The app", "How it works", "Plans", "Help"],
  download: "Download app", freeDownload: "Download for free", how: "How it works", menu: "Open menu", closeMenu: "Close menu",
  hero: ["Less bill splitting.", "More plans.", "More living."],
  intro: "Split group expenses and organize your personal finances. All in Teilen, so you can focus on enjoying life.",
  available: "Available on iOS and Android", pillars: ["Shared expenses", "Personal finances", "Savings goals"],
  dinner: "Dinner with friends", dinnerDetail: "4 people · CLP $12,000 each", example: "Illustrative example in Chilean pesos",
  sharingTitle: "Sharing is easy.\nSo are the expenses.", sharingIntro: "From the first coffee to the last day of your trip, every expense has its place.",
  cases: [
    {tab: "With friends", title: "Enjoy the trip.\nShare the expenses.", description: "Create a group, add what each person paid and let Teilen calculate the balances.", steps: ["Create a group and invite friends", "Add and split expenses", "See who owes whom"], details: ["Share your group's link or QR code with everyone joining the plan.", "Record who paid and split equally, by percentage or by custom amounts.", "Check balances and record payments as they happen to keep everything clear."], link: "Explore shared expenses", href: "/gastos-compartidos", group: "Southern getaway", people: "3 people", rows: ["Cabin", "Groceries", "Fuel"], payers: ["Cami paid", "Nico paid", "You paid"], amounts: [90000, 30000, 15000], total: "Group total", resultLabel: "Each person's share", result: 45000},
    {tab: "As a couple", title: "More teamwork.\nLess ‘who paid?’.", description: "From rent to that special dinner. Keep your shared expenses and balances close at hand.", steps: ["Create your shared space", "Split things your way", "Keep the numbers clear"], details: ["A group for your home, your holidays or a project you're working on together.", "Split each expense equally, by percentage or by custom amounts.", "Review transactions together and record completed payments."], link: "Discover how to split expenses", href: "/dividir-gastos", group: "Our home", people: "2 people", rows: ["Groceries", "Friday dinner", "Internet"], payers: ["Dani paid", "You paid", "Dani paid"], amounts: [60000, 40000, 20000], total: "Shared total", resultLabel: "When splitting equally", result: 60000},
    {tab: "With roommates", title: "Share your home.\nAnd peace of mind.", description: "Rent, utilities and shared purchases in one place. Everyone knows what they paid and what their share is.", steps: ["Invite the whole household", "Add shared expenses", "Check everyone's balance"], details: ["Create a group and share its invitation link.", "Add expenses and choose who takes part in each one.", "Your shared history helps answer questions without searching through messages."], link: "Organize household expenses", href: "/gastos-compartidos", group: "Our shared apartment", people: "3 people", rows: ["Rent", "Electricity", "Internet"], payers: ["Fran paid", "Alex paid", "You paid"], amounts: [450000, 30000, 30000], total: "Household total", resultLabel: "Each person's share", result: 170000},
    {tab: "For you", title: "Your month,\nwith a clearer picture.", description: "Record personal income and expenses, review your categories and track your savings goals.", steps: ["Record your transactions", "See where your money goes", "Work toward your goals"], details: ["Keep personal income and expenses in your own space.", "Review your activity and statistics to understand your month better.", "Create a goal and record your contributions to see your progress."], link: "Explore personal finances", href: "/control-de-gastos", group: "My monthly expenses", people: "My personal space", rows: ["Groceries", "Transport", "Coffee and going out"], payers: ["Food", "Getting around", "Free time"], amounts: [90000, 30000, 15000], total: "Recorded total", resultLabel: "Personal expenses organized", result: 135000},
  ],
  calculator: "Try it with your next plan", amountLabel: "Total expense (CLP)", peopleLabel: "People", perPerson: "per person", calculatorHint: "Split equally. For other arrangements, choose percentages or custom amounts in the app.", invalid: "Enter a valid amount and between 2 and 100 people.", remainder: "The total cannot be split exactly in whole pesos: some people pay $1 more to make up the total.",
  featuresTitle: "Your money,\nwith more clarity.", featuresIntro: "Shared and personal finances, in one app.", goalTitle: "Make room for\nyour next big plan.", goalDescription: "Record your personal expenses and track your savings goals.", goalName: "Trip to the south", goalOf: "of", goalExample: "Example savings goal", goalLink: "Discover savings goals",
  features: [
    {title: "Less typing, more time", description: "Scan your receipts with AI and review the details before saving.", href: "/dividir-gastos"},
    {title: "Stay ahead of your bills", description: "Organize recurring expenses and due date reminders.", href: "/recordatorios"},
    {title: "Understand your spending", description: "Review your activity, categories and reports.", href: "/control-de-gastos"},
  ],
  life: "Life happens outside\na spreadsheet.", lifeIntro: "Make more plans. Teilen helps with the expenses.",
  plansTitle: "Start free.\nGrow at your pace.", plansIntro: "Choose how you want to get organized.", freeTitle: "Teilen Free", freeIntro: "Start getting your finances in order.", freeFeatures: ["Shared and personal expenses", "Up to 3 active groups", "Savings goals", "Up to 3 AI receipt scans per month"], freeCta: "Start for free",
  premiumTitle: "Teilen Premium", premiumBadge: "More possibilities", premiumIntro: "For those ready to take things further.", premiumValue: "Your next level", premiumPriceMonthly: "CLP $3,980 / month", premiumPriceMonthlyUsd: "≈ US$4.15 / month", premiumPriceAnnual: "or CLP $19,990 / year · ≈ US$21", premiumFeatures: ["Unlimited groups and scans", "PDF and Excel reports", "Recurring expenses and installments", "Investment tracking"], premiumCta: "Explore Premium", planNote: "USD values are approximate and may vary with the exchange rate. Subscriptions are managed through the App Store or Google Play.",
  faqTitle: "Clear from\nthe start.", faqMore: "See all questions", faqs: [
    {question: "What can I do with Teilen?", answer: "You can split expenses with friends, your partner or roommates; record personal income and expenses; create reminders and track savings goals. All in one app."},
    {question: "Is it free?", answer: "Yes. The Free plan includes personal expenses, up to 5 shared expenses per day, up to 3 active groups, savings goals, up to 3 AI receipt scans per month, and up to 3 reminders. Premium raises those limits and adds advanced features. Check current limits and prices in the app."},
    {question: "Does Teilen move my money?", answer: "No. Teilen organizes your expenses, calculates balances and lets you record payments you've already made. You make transfers using the method you agree on with the other people. Goals and investments are tracking records, not accounts that hold your funds."},
    {question: "Is it available on iOS and Android?", answer: "Yes. Download Teilen from the App Store or Google Play. You can share a group with people using either operating system."},
  ],
  closingTitle: "Your next plan\nstarts with Teilen.", closingIntro: "Clear expenses. More life ahead.",
  footerDescription: "What you share and what's yours. Make your finances clearer with Teilen.", footerHeadings: ["Product", "Help", "Legal"], footerProduct: ["Split expenses", "Shared expenses", "Personal finances", "Savings goals", "Premium"], footerHelp: ["Help center", "Frequently asked questions", "Contact"], footerLegal: ["Privacy", "Terms and conditions", "Cookies"], madeIn: "Made in Chile, for your plans.", allRights: "All rights reserved.",
};
