import type { MarketingCopy } from "../marketing-copy";

export const frenchMarketing: MarketingCopy = {
  nav: ["L'app", "Comment ça marche", "Offres", "Aide"],
  download: "Télécharger l'app", freeDownload: "Télécharger gratuitement", how: "Comment ça marche", menu: "Ouvrir le menu", closeMenu: "Fermer le menu",
  hero: ["Moins de comptes.", "Plus de projets.", "Plus de vie."],
  intro: "Partage tes dépenses de groupe et organise tes finances personnelles. Tout dans Teilen, pour continuer à profiter de ce qui compte.",
  available: "Disponible sur iOS et Android", pillars: ["Dépenses partagées", "Finances personnelles", "Objectifs d'épargne"],
  dinner: "Dîner entre amis", dinnerDetail: "4 personnes · CLP $12 000 chacune", example: "Exemple illustratif en pesos chiliens",
  sharingTitle: "Partager, c'est facile.\nFaire les comptes aussi.", sharingIntro: "Du premier café au dernier jour du voyage, chaque dépense a sa place.",
  cases: [
    {tab: "Entre amis", title: "Profitez du voyage.\nPartagez les dépenses.", description: "Crée un groupe, ajoute ce que chaque personne a payé et laisse Teilen calculer les soldes.", steps: ["Crée un groupe et invite", "Ajoute et partage les dépenses", "Vérifie qui doit à qui"], details: ["Partage le lien ou le code QR du groupe avec les personnes qui se joignent à vous.", "Indique qui a payé et répartis à parts égales, par pourcentage ou avec des montants personnalisés.", "Consulte les soldes et enregistre les paiements effectués pour garder des comptes clairs."], link: "Explorer les dépenses partagées", href: "/gastos-compartidos", group: "Escapade dans le sud", people: "3 personnes", rows: ["Chalet", "Courses", "Carburant"], payers: ["Cami a payé", "Nico a payé", "Tu as payé"], amounts: [90000, 30000, 15000], total: "Total du groupe", resultLabel: "La part de chaque personne", result: 45000},
    {tab: "En couple", title: "Plus d'esprit d'équipe.\nMoins de « qui a payé ? ».", description: "Du loyer à ce dîner spécial. Gardez vos dépenses et vos soldes communs à portée de main.", steps: ["Créez votre espace partagé", "Répartissez à votre façon", "Gardez des comptes clairs"], details: ["Un groupe pour la maison, les vacances ou le projet que vous avez en commun.", "Répartissez chaque dépense à parts égales, par pourcentage ou avec des montants personnalisés.", "Consultez ensemble les opérations et enregistrez les paiements effectués."], link: "Découvrir comment partager les dépenses", href: "/dividir-gastos", group: "Chez nous", people: "2 personnes", rows: ["Courses", "Dîner du vendredi", "Internet"], payers: ["Dani a payé", "Tu as payé", "Dani a payé"], amounts: [60000, 40000, 20000], total: "Total partagé", resultLabel: "En partageant à parts égales", result: 60000},
    {tab: "En colocation", title: "Partagez un toit.\nEt la tranquillité.", description: "Loyer, charges et achats communs au même endroit. Chaque personne sait ce qu'elle a payé et quelle est sa part.", steps: ["Invitez toute la colocation", "Notez les dépenses communes", "Consultez le solde de chacun"], details: ["Créez un groupe et partagez son lien d'invitation.", "Ajoutez les dépenses et choisissez qui participe à chacune.", "L'historique partagé aide à répondre aux questions sans fouiller dans les messages."], link: "Organiser les dépenses du foyer", href: "/gastos-compartidos", group: "Notre colocation", people: "3 personnes", rows: ["Loyer", "Électricité", "Internet"], payers: ["Fran a payé", "Alex a payé", "Tu as payé"], amounts: [450000, 30000, 30000], total: "Total du foyer", resultLabel: "La part de chaque personne", result: 170000},
    {tab: "Pour toi", title: "Ton mois,\nen plus clair.", description: "Enregistre tes revenus et dépenses personnels, consulte tes catégories et suis tes objectifs d'épargne.", steps: ["Enregistre tes opérations", "Vois où va ton argent", "Avance vers tes objectifs"], details: ["Garde tes revenus et dépenses personnels dans ton propre espace.", "Consulte ton activité et tes statistiques pour mieux comprendre ton mois.", "Crée un objectif et enregistre tes contributions pour voir tes progrès."], link: "Explorer les finances personnelles", href: "/control-de-gastos", group: "Mes dépenses du mois", people: "Mon espace personnel", rows: ["Courses", "Transports", "Cafés et sorties"], payers: ["Alimentation", "Mobilité", "Loisirs"], amounts: [90000, 30000, 15000], total: "Total enregistré", resultLabel: "Dépenses personnelles organisées", result: 135000},
  ],
  calculator: "Essaie pour ta prochaine sortie", amountLabel: "Montant total de la dépense (CLP)", peopleLabel: "Personnes", perPerson: "par personne", calculatorHint: "Partage à parts égales. Pour d'autres arrangements, choisis des pourcentages ou des montants personnalisés dans l'app.", invalid: "Saisis un montant valide et un nombre de personnes entre 2 et 100.", remainder: "Le partage ne tombe pas juste en pesos : certaines personnes paient $1 de plus pour atteindre le total.",
  featuresTitle: "Ton argent,\nen plus clair.", featuresIntro: "Finances partagées et personnelles, dans une seule app.", goalTitle: "Fais de la place pour\nton prochain grand projet.", goalDescription: "Enregistre tes dépenses personnelles et suis tes objectifs d'épargne.", goalName: "Voyage dans le sud", goalOf: "sur", goalExample: "Exemple d'objectif", goalLink: "Découvrir les objectifs d'épargne",
  features: [
    {title: "Moins de saisie, plus de temps", description: "Scanne tes reçus avec l'IA et vérifie les données avant de les enregistrer.", href: "/dividir-gastos"},
    {title: "Garde une longueur d'avance sur tes factures", description: "Organise les dépenses récurrentes et les rappels d'échéance.", href: "/recordatorios"},
    {title: "Comprends tes dépenses", description: "Consulte ton activité, tes catégories et tes rapports.", href: "/control-de-gastos"},
  ],
  life: "La vie se passe\nen dehors d'un tableur.", lifeIntro: "Faites plus de projets. Teilen vous aide avec les comptes.",
  plansTitle: "Commence gratuitement.\nÉvolue à ton rythme.", plansIntro: "Choisis comment tu veux t'organiser.", freeTitle: "Teilen Gratuit", freeIntro: "Pour commencer à mettre tes comptes en ordre.", freeFeatures: ["Dépenses partagées et personnelles", "Jusqu'à 10 groupes", "Objectifs d'épargne", "10 scans de reçus avec IA"], freeCta: "Commencer gratuitement",
  premiumTitle: "Teilen Premium", premiumBadge: "Plus de possibilités", premiumIntro: "Pour celles et ceux qui veulent aller plus loin.", premiumValue: "Passe au niveau supérieur", premiumFeatures: ["Groupes et scans illimités", "Rapports en PDF et CSV", "Dépenses récurrentes et paiements échelonnés", "Suivi des investissements"], premiumCta: "Découvrir Premium", planNote: "Consulte les prix, limites et conditions en vigueur dans l'app. Les abonnements sont gérés sur l'App Store ou Google Play.",
  faqTitle: "Tout est clair,\ndès le départ.", faqMore: "Voir toutes les questions", faqs: [
    {question: "Que puis-je faire avec Teilen ?", answer: "Tu peux partager les dépenses avec des amis, ton ou ta partenaire ou tes colocataires ; enregistrer tes revenus et dépenses personnels ; créer des rappels et suivre tes objectifs d'épargne. Le tout dans une seule app."},
    {question: "Est-ce gratuit ?", answer: "Oui. Tu peux commencer avec l'offre Gratuite, qui comprend les dépenses partagées et personnelles, jusqu'à 10 groupes, les objectifs d'épargne et les scans de reçus avec IA. Premium augmente les limites et ajoute des fonctions avancées. Consulte les limites et les prix en vigueur dans l'app."},
    {question: "Teilen déplace-t-il mon argent ?", answer: "Non. Teilen organise tes dépenses, calcule les soldes et permet d'enregistrer les paiements déjà effectués. Tu fais les virements par le moyen convenu avec les autres personnes. Les objectifs et les investissements sont des outils de suivi, pas des comptes qui conservent tes fonds."},
    {question: "L'app est-elle disponible sur iOS et Android ?", answer: "Oui. Télécharge Teilen sur l'App Store ou Google Play. Tu peux partager un groupe avec des personnes utilisant l'un ou l'autre système."},
  ],
  closingTitle: "Ton prochain projet\ncommence avec Teilen.", closingIntro: "Des comptes clairs. La vie devant toi.",
  footerDescription: "Ce que tu partages et ce qui t'appartient. Tes comptes, plus clairs avec Teilen.", footerHeadings: ["Produit", "Aide", "Informations légales"], footerProduct: ["Partager les dépenses", "Dépenses partagées", "Finances personnelles", "Objectifs d'épargne", "Premium"], footerHelp: ["Centre d'aide", "Questions fréquentes", "Contact"], footerLegal: ["Confidentialité", "Conditions générales", "Cookies"], madeIn: "Créé au Chili, pour tes projets.", allRights: "Tous droits réservés.",
};
