import type { MarketingCopy } from "../marketing-copy";

export const italianMarketing: MarketingCopy = {
  nav: ["L'app", "Come funziona", "Piani", "Aiuto"],
  download: "Scarica l'app", freeDownload: "Scarica gratis", how: "Come funziona", menu: "Apri menu", closeMenu: "Chiudi menu",
  hero: ["Meno conti.", "Più progetti.", "Più vita."],
  intro: "Dividi le spese di gruppo e organizza le tue finanze personali. Tutto su Teilen, per continuare a goderti ciò che conta.",
  available: "Disponibile per iOS e Android", pillars: ["Spese condivise", "Finanze personali", "Obiettivi di risparmio"],
  dinner: "Cena con amici", dinnerDetail: "4 persone · CLP $12.000 a testa", example: "Esempio illustrativo in pesos cileni",
  sharingTitle: "Condividere è facile.\nAnche fare i conti.", sharingIntro: "Dal primo caffè all'ultimo giorno di viaggio, ogni spesa ha il suo posto.",
  cases: [
    {tab: "Con amici", title: "Godetevi il viaggio.\nCondividete le spese.", description: "Crea un gruppo, aggiungi ciò che ha pagato ogni persona e lascia che Teilen calcoli i saldi.", steps: ["Crea un gruppo e invita", "Aggiungi e dividi le spese", "Scopri chi deve a chi"], details: ["Condividi il link o il codice QR del gruppo con chi partecipa.", "Registra chi ha pagato e dividi in parti uguali, per percentuale o con importi personalizzati.", "Consulta i saldi e registra i pagamenti effettuati per tenere i conti in chiaro."], link: "Esplora le spese condivise", href: "/gastos-compartidos", group: "Fuga al sud", people: "3 persone", rows: ["Chalet", "Supermercato", "Carburante"], payers: ["Ha pagato Cami", "Ha pagato Nico", "Hai pagato tu"], amounts: [90000, 30000, 15000], total: "Totale del gruppo", resultLabel: "La quota di ogni persona", result: 45000},
    {tab: "In coppia", title: "Più squadra.\nMeno «chi ha pagato?».", description: "Dall'affitto a quella cena speciale. Tenete a portata di mano le spese e i saldi che condividete.", steps: ["Create il vostro spazio condiviso", "Dividete a modo vostro", "Tenete i conti in chiaro"], details: ["Un gruppo per la casa, le vacanze o il progetto che avete in comune.", "Dividete ogni spesa in parti uguali, per percentuale o con importi personalizzati.", "Controllate insieme i movimenti e registrate i pagamenti effettuati."], link: "Scopri come dividere le spese", href: "/dividir-gastos", group: "Casa nostra", people: "2 persone", rows: ["Supermercato", "Cena del venerdì", "Internet"], payers: ["Ha pagato Dani", "Hai pagato tu", "Ha pagato Dani"], amounts: [60000, 40000, 20000], total: "Totale condiviso", resultLabel: "Dividendo in parti uguali", result: 60000},
    {tab: "Con coinquilini", title: "Condividete la casa.\nAnche la tranquillità.", description: "Affitto, bollette e acquisti comuni in un unico posto. Ogni persona sa cosa ha pagato e qual è la sua quota.", steps: ["Invitate tutti i coinquilini", "Annotate le spese comuni", "Consultate il saldo di ognuno"], details: ["Create un gruppo e condividete il link di invito.", "Aggiungete le spese e scegliete chi partecipa a ciascuna.", "La cronologia condivisa aiuta a chiarire i dubbi senza cercare tra i messaggi."], link: "Organizza le spese di casa", href: "/gastos-compartidos", group: "Appartamento condiviso", people: "3 persone", rows: ["Affitto", "Elettricità", "Internet"], payers: ["Ha pagato Fran", "Ha pagato Alex", "Hai pagato tu"], amounts: [450000, 30000, 30000], total: "Totale della casa", resultLabel: "La quota di ogni persona", result: 170000},
    {tab: "Per te", title: "Il tuo mese,\ncon tutto più chiaro.", description: "Registra entrate e spese personali, controlla le categorie e segui i tuoi obiettivi di risparmio.", steps: ["Registra i tuoi movimenti", "Scopri dove spendi", "Avanza verso i tuoi obiettivi"], details: ["Tieni le entrate e le spese personali nel tuo spazio.", "Consulta l'attività e le statistiche per capire meglio il tuo mese.", "Crea un obiettivo e registra i tuoi contributi per vedere i progressi."], link: "Esplora le finanze personali", href: "/control-de-gastos", group: "Le mie spese del mese", people: "Il mio spazio personale", rows: ["Supermercato", "Trasporti", "Caffè e uscite"], payers: ["Alimentazione", "Mobilità", "Tempo libero"], amounts: [90000, 30000, 15000], total: "Totale registrato", resultLabel: "Spese personali organizzate", result: 135000},
  ],
  calculator: "Provalo per la tua prossima uscita", amountLabel: "Totale della spesa (CLP)", peopleLabel: "Persone", perPerson: "a persona", calculatorHint: "Divisione in parti uguali. Per altri accordi, scegli percentuali o importi personalizzati nell'app.", invalid: "Inserisci un importo valido e un numero di persone tra 2 e 100.", remainder: "La divisione non è esatta in pesos: alcune persone pagano $1 in più per raggiungere il totale.",
  featuresTitle: "I tuoi soldi,\ncon più chiarezza.", featuresIntro: "Finanze condivise e personali, in un'unica app.", goalTitle: "Fai spazio al tuo\nprossimo grande progetto.", goalDescription: "Registra le spese personali e segui i tuoi obiettivi di risparmio.", goalName: "Viaggio al sud", goalOf: "di", goalExample: "Esempio di un obiettivo", goalLink: "Scopri gli obiettivi di risparmio",
  features: [
    {title: "Meno digitazioni, più tempo", description: "Scansiona gli scontrini con l'IA e controlla i dati prima di salvare.", href: "/dividir-gastos"},
    {title: "Nessuna sorpresa con le bollette", description: "Organizza spese ricorrenti e promemoria delle scadenze.", href: "/recordatorios"},
    {title: "Capisci dove spendi", description: "Consulta attività, categorie e report.", href: "/control-de-gastos"},
  ],
  life: "La vita è fuori\nda un foglio di calcolo.", lifeIntro: "Fate più progetti. Teilen vi aiuta con i conti.",
  plansTitle: "Inizia gratis.\nCresci al tuo ritmo.", plansIntro: "Scegli come vuoi organizzarti.", freeTitle: "Teilen Gratis", freeIntro: "Per iniziare a mettere in ordine i conti.", freeFeatures: ["Spese condivise e personali", "Fino a 10 gruppi", "Obiettivi di risparmio", "10 scansioni di scontrini con IA"], freeCta: "Inizia gratis",
  premiumTitle: "Teilen Premium", premiumBadge: "Più possibilità", premiumIntro: "Per chi vuole fare un passo in più.", premiumValue: "Il tuo prossimo livello", premiumFeatures: ["Gruppi e scansioni illimitati", "Report in PDF e CSV", "Spese ricorrenti e rate", "Monitoraggio degli investimenti"], premiumCta: "Scopri Premium", planNote: "Consulta prezzi, limiti e condizioni attuali nell'app. Gli abbonamenti vengono gestiti tramite App Store o Google Play.",
  faqTitle: "Tutto chiaro,\nfin dall'inizio.", faqMore: "Vedi tutte le domande", faqs: [
    {question: "Cosa posso fare con Teilen?", answer: "Puoi dividere le spese con amici, partner o coinquilini; registrare entrate e spese personali; creare promemoria e seguire obiettivi di risparmio. Tutto in un'unica app."},
    {question: "È gratis?", answer: "Sì. Puoi iniziare con il piano Gratis, che include spese condivise e personali, fino a 10 gruppi, obiettivi di risparmio e scansioni di scontrini con IA. Premium aumenta i limiti e aggiunge funzionalità avanzate. Controlla i limiti e i prezzi attuali nell'app."},
    {question: "Teilen sposta i miei soldi?", answer: "No. Teilen organizza le spese, calcola i saldi e permette di registrare pagamenti già effettuati. Esegui i trasferimenti con il metodo concordato con le altre persone. Obiettivi e investimenti sono registri di monitoraggio, non conti di custodia."},
    {question: "È disponibile per iOS e Android?", answer: "Sì. Scarica Teilen dall'App Store o da Google Play. Puoi condividere un gruppo con persone che usano uno qualsiasi dei due sistemi."},
  ],
  closingTitle: "Il tuo prossimo progetto\ninizia con Teilen.", closingIntro: "I conti in chiaro. La vita davanti.",
  footerDescription: "Ciò che condividi e ciò che è tuo. I tuoi conti, più chiari con Teilen.", footerHeadings: ["Prodotto", "Aiuto", "Legale"], footerProduct: ["Dividere le spese", "Spese condivise", "Finanze personali", "Obiettivi di risparmio", "Premium"], footerHelp: ["Centro assistenza", "Domande frequenti", "Contatti"], footerLegal: ["Privacy", "Termini e condizioni", "Cookie"], madeIn: "Creato in Cile, per i tuoi progetti.", allRights: "Tutti i diritti riservati.",
};
