import type { MarketingCopy } from "../marketing-copy";

export const portugueseMarketing: MarketingCopy = {
  nav: ["O app", "Como funciona", "Planos", "Ajuda"],
  download: "Baixar o app", freeDownload: "Baixar grátis", how: "Como funciona", menu: "Abrir menu", closeMenu: "Fechar menu",
  hero: ["Menos contas.", "Mais planos.", "Mais vida."],
  intro: "Divida despesas em grupo e organize suas finanças pessoais. Tudo no Teilen, para você continuar aproveitando o que importa.",
  available: "Disponível para iOS e Android", pillars: ["Despesas compartilhadas", "Finanças pessoais", "Metas de economia"],
  dinner: "Jantar com amigos", dinnerDetail: "4 pessoas · CLP $12.000 cada", example: "Exemplo ilustrativo em pesos chilenos",
  sharingTitle: "Compartilhar é fácil.\nDividir as contas também.", sharingIntro: "Do primeiro café ao último dia da viagem, cada despesa tem seu lugar.",
  cases: [
    {tab: "Com amigos", title: "Aproveitem a viagem.\nCompartilhem as despesas.", description: "Crie um grupo, adicione o que cada pessoa pagou e deixe o Teilen calcular os saldos.", steps: ["Crie um grupo e convide", "Adicione e divida as despesas", "Veja quem deve a quem"], details: ["Compartilhe o link ou o QR code do grupo com quem vai participar.", "Registre quem pagou e divida em partes iguais, por porcentagem ou com valores personalizados.", "Consulte os saldos e registre os pagamentos realizados para manter as contas claras."], link: "Explorar despesas compartilhadas", href: "/gastos-compartidos", group: "Escapada para o sul", people: "3 pessoas", rows: ["Chalé", "Supermercado", "Combustível"], payers: ["Cami pagou", "Nico pagou", "Você pagou"], amounts: [90000, 30000, 15000], total: "Total do grupo", resultLabel: "A parte de cada pessoa", result: 45000},
    {tab: "Em casal", title: "Mais parceria.\nMenos ‘quem pagou?’.", description: "Do aluguel àquele jantar especial. Tenham sempre à mão as despesas e os saldos que compartilham.", steps: ["Criem seu espaço compartilhado", "Dividam do jeito de vocês", "Mantenham as contas claras"], details: ["Um grupo para a casa, as férias ou o projeto que vocês têm em comum.", "Dividam cada despesa em partes iguais, por porcentagem ou com valores personalizados.", "Confiram as movimentações juntos e registrem os pagamentos realizados."], link: "Descobrir como dividir despesas", href: "/dividir-gastos", group: "Nossa casa", people: "2 pessoas", rows: ["Supermercado", "Jantar de sexta", "Internet"], payers: ["Dani pagou", "Você pagou", "Dani pagou"], amounts: [60000, 40000, 20000], total: "Total compartilhado", resultLabel: "Ao dividir em partes iguais", result: 60000},
    {tab: "Com colegas de casa", title: "Compartilhem a casa.\nE a tranquilidade.", description: "Aluguel, contas e compras em comum em um só lugar. Cada pessoa sabe o que pagou e qual é a sua parte.", steps: ["Convidem toda a casa", "Anotem as despesas em comum", "Consultem o saldo de cada pessoa"], details: ["Criem um grupo e compartilhem o link de convite.", "Adicionem as despesas e escolham quem participa de cada uma.", "O histórico compartilhado ajuda a tirar dúvidas sem procurar nas mensagens."], link: "Organizar as despesas da casa", href: "/gastos-compartidos", group: "Apê compartilhado", people: "3 pessoas", rows: ["Aluguel", "Energia elétrica", "Internet"], payers: ["Fran pagou", "Alex pagou", "Você pagou"], amounts: [450000, 30000, 30000], total: "Total da casa", resultLabel: "A parte de cada pessoa", result: 170000},
    {tab: "Para você", title: "Seu mês,\ncom tudo mais claro.", description: "Registre receitas e despesas pessoais, confira suas categorias e acompanhe suas metas de economia.", steps: ["Registre suas movimentações", "Veja com o que está gastando", "Avance em direção às suas metas"], details: ["Mantenha suas receitas e despesas pessoais no seu próprio espaço.", "Consulte sua atividade e as estatísticas para entender melhor o seu mês.", "Crie uma meta e registre suas contribuições para ver seu progresso."], link: "Explorar finanças pessoais", href: "/control-de-gastos", group: "Minhas despesas do mês", people: "Meu espaço pessoal", rows: ["Supermercado", "Transporte", "Cafés e passeios"], payers: ["Alimentação", "Mobilidade", "Lazer"], amounts: [90000, 30000, 15000], total: "Total registrado", resultLabel: "Despesas pessoais organizadas", result: 135000},
  ],
  calculator: "Experimente com seu próximo plano", amountLabel: "Total da despesa (CLP)", peopleLabel: "Pessoas", perPerson: "por pessoa", calculatorHint: "Divisão em partes iguais. Para outros acordos, escolha porcentagens ou valores personalizados no app.", invalid: "Insira um valor válido e entre 2 e 100 pessoas.", remainder: "A divisão não é exata em pesos: algumas pessoas pagam $1 a mais para completar o total.",
  featuresTitle: "Seu dinheiro,\ncom mais clareza.", featuresIntro: "O compartilhado e o pessoal, em um só app.", goalTitle: "Abra espaço para\nseu próximo grande plano.", goalDescription: "Registre suas despesas pessoais e acompanhe suas metas de economia.", goalName: "Viagem ao sul", goalOf: "de", goalExample: "Exemplo de uma meta", goalLink: "Conhecer as metas de economia",
  features: [
    {title: "Menos digitação, mais tempo", description: "Digitalize seus comprovantes com IA e confira os dados antes de salvar.", href: "/dividir-gastos"},
    {title: "Sem surpresas com as contas", description: "Organize despesas recorrentes e lembretes de vencimento.", href: "/recordatorios"},
    {title: "Entenda seus gastos", description: "Consulte sua atividade, categorias e relatórios.", href: "/control-de-gastos"},
  ],
  life: "A vida acontece fora\nde uma planilha.", lifeIntro: "Façam mais planos. O Teilen ajuda com as contas.",
  plansTitle: "Comece grátis.\nCresça no seu ritmo.", plansIntro: "Escolha como quer se organizar.", freeTitle: "Teilen Grátis", freeIntro: "Para começar a colocar as contas em ordem.", freeFeatures: ["Despesas compartilhadas e pessoais", "Até 3 grupos ativos", "Metas de economia", "Até 3 digitalizações de comprovantes com IA por mês"], freeCta: "Começar grátis",
  premiumTitle: "Teilen Premium", premiumBadge: "Mais possibilidades", premiumIntro: "Para quem quer dar um passo além.", premiumValue: "Seu próximo nível", premiumPriceMonthly: "CLP $3.980 / mês", premiumPriceMonthlyUsd: "≈ US$4,15 / mês", premiumPriceAnnual: "ou CLP $19.990 / ano · ≈ US$21", premiumFeatures: ["Grupos e digitalizações ilimitados", "Relatórios em PDF e Excel", "Despesas recorrentes e parcelas", "Acompanhamento de investimentos"], premiumCta: "Conhecer o Premium", planNote: "Os valores em USD são aproximados e podem variar conforme o câmbio. As assinaturas são gerenciadas pela App Store ou pelo Google Play.",
  faqTitle: "Tudo claro,\ndesde o início.", faqMore: "Ver todas as perguntas", faqs: [
    {question: "O que posso fazer com o Teilen?", answer: "Você pode dividir despesas com amigos, seu par ou colegas de casa; registrar receitas e despesas pessoais; criar lembretes e acompanhar metas de economia. Tudo em um só app."},
    {question: "É grátis?", answer: "Sim. O plano Grátis inclui despesas pessoais, até 5 despesas compartilhadas por dia, até 3 grupos ativos, metas de economia, até 3 digitalizações de comprovantes com IA por mês e até 3 lembretes. O Premium amplia esses limites e adiciona funções avançadas. Confira os limites e preços atuais no app."},
    {question: "O Teilen movimenta meu dinheiro?", answer: "Não. O Teilen organiza suas despesas, calcula saldos e permite registrar pagamentos que você já realizou. As transferências são feitas pelo meio combinado com as outras pessoas. Metas e investimentos são registros de acompanhamento, não contas de custódia."},
    {question: "Está disponível para iOS e Android?", answer: "Sim. Baixe o Teilen na App Store ou no Google Play. Você pode compartilhar um grupo com pessoas que usam qualquer um dos dois sistemas."},
  ],
  closingTitle: "Seu próximo plano\ncomeça com o Teilen.", closingIntro: "As contas claras. A vida pela frente.",
  footerDescription: "O que você compartilha e o que é seu. Suas contas mais claras com o Teilen.", footerHeadings: ["Produto", "Ajuda", "Legal"], footerProduct: ["Dividir despesas", "Despesas compartilhadas", "Finanças pessoais", "Metas de economia", "Premium"], footerHelp: ["Central de ajuda", "Perguntas frequentes", "Contato"], footerLegal: ["Privacidade", "Termos e condições", "Cookies"], madeIn: "Feito no Chile, para seus planos.", allRights: "Todos os direitos reservados.",
};
